services:
  - type: web
    name: taiwan-stock-ai-python-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: GROQ_API_KEY
        sync: false
